
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Sat Nov 24 15:17:56 PST 2001
//----------------------------------------------------

package org.dgould.geb.bloop;

import java_cup.runtime.*;
import org.dgould.geb.bloop.ast.*;
import org.dgould.*;

public class CallParser extends java_cup.runtime.lr_parser {

  /** constructor */
  public CallParser() {super();}

  /** production table */
  protected static final short _production_table[][] = {
        {0, 2},     {1, 2},     {1, 2},     {1, 2},     {1, 2}, 
        {3, 3},     {3, 1},     {4, 0},     {4, 1},     {5, 3}, 
        {5, 1},     {6, 0},     {6, 1},     {7, 2},     {7, 1}, 
        {9, 1},     {9, 1},     {9, 1},     {9, 1},     {9, 1}, 
        {9, 1},     {9, 1},     {9, 3},     {10, 4},     {11, 4}, 
        {12, 2},     {12, 3},     {12, 3},     {12, 3},     {12, 3}, 
        {12, 3},     {12, 3},     {12, 3},     {12, 3},     {12, 3}, 
        {2, 11},     {8, 9},     {13, 1},     {13, 1},     {13, 1}, 
        {13, 1},     {13, 1},     {13, 1},     {14, 2},     {15, 7}, 
        {15, 5},     {16, 6},     {17, 4},     {17, 7},     {18, 4}, 
        {19, 4}  };

  /** access to production table */
  public short[][] production_table() {return _production_table;}

  /** parse action table */
  protected static final short[][] _action_table = {
    /*0*/{6,2,-1,0},
    /*1*/{10,5,-1,0},
    /*2*/{0,4,-1,0},
    /*3*/{0,-1,-1,0},
    /*4*/{3,6,4,14,5,10,6,15,7,16,11,-8,14,8,20,17,-1,0},
    /*5*/{11,-16,13,-16,15,-16,18,-16,22,-16,23,-16,24,-16,25,-16,26,-16,27,-16,28,-16,29,-16,30,-16,-1,0},
    /*6*/{11,-9,-1,0},
    /*7*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*8*/{11,-21,13,-21,15,-21,18,-21,22,-21,23,-21,24,-21,25,-21,26,-21,27,-21,28,-21,29,-21,30,-21,-1,0},
    /*9*/{11,-18,13,-18,15,-18,18,-18,22,-18,23,-18,24,-18,25,-18,26,-18,27,-18,28,-18,29,-18,30,-18,-1,0},
    /*10*/{11,-22,13,-22,15,-22,18,-22,22,-22,23,-22,24,-22,25,-22,26,-22,27,-22,28,-22,29,-22,30,-22,-1,0},
    /*11*/{11,-20,13,-20,15,-20,18,-20,22,-20,23,-20,24,-20,25,-20,26,-20,27,-20,28,-20,29,-20,30,-20,-1,0},
    /*12*/{11,-7,18,42,22,21,23,29,24,27,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*13*/{11,-17,13,-17,15,-17,18,-17,22,-17,23,-17,24,-17,25,-17,26,-17,27,-17,28,-17,29,-17,30,-17,-1,0},
    /*14*/{10,5,11,-19,13,-19,15,-19,18,-19,22,-19,23,-19,24,-19,25,-19,26,-19,27,-19,28,-19,29,-19,30,-19,-1,0},
    /*15*/{12,39,-1,0},
    /*16*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*17*/{11,19,-1,0},
    /*18*/{0,-25,11,-25,13,-25,15,-25,18,-25,22,-25,23,-25,24,-25,25,-25,26,-25,27,-25,28,-25,29,-25,30,-25,-1,0},
    /*19*/{11,-26,13,-26,15,-26,18,-26,22,21,23,29,24,27,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*20*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*21*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*22*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*23*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*24*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*25*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*26*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*27*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*28*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*29*/{11,-28,13,-28,15,-28,18,-28,22,-28,23,-28,24,27,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*30*/{11,-32,13,-32,15,-32,18,-32,22,-32,23,-32,24,-32,25,-32,26,-32,27,-32,28,-32,29,-32,30,-32,-1,0},
    /*31*/{11,-29,13,-29,15,-29,18,-29,22,-29,23,-29,24,-29,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*32*/{11,-30,13,-30,15,-30,18,-30,22,-30,23,-30,24,-30,25,-30,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*33*/{11,-34,13,-34,15,-34,18,-34,22,-34,23,-34,24,-34,25,-34,26,24,27,28,28,-34,29,-34,30,-34,-1,0},
    /*34*/{11,-31,13,-31,15,-31,18,-31,22,-31,23,-31,24,-31,25,-31,26,-31,27,-31,28,-31,29,-31,30,-31,-1,0},
    /*35*/{11,-33,13,-33,15,-33,18,-33,22,-33,23,-33,24,-33,25,-33,26,24,27,28,28,-33,29,-33,30,-33,-1,0},
    /*36*/{11,-35,13,-35,15,-35,18,-35,22,-35,23,-35,24,-35,25,-35,26,24,27,28,28,-35,29,-35,30,-35,-1,0},
    /*37*/{11,-27,13,-27,15,-27,18,-27,22,-27,23,29,24,27,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*38*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*39*/{13,41,22,21,23,29,24,27,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*40*/{11,-24,13,-24,15,-24,18,-24,22,-24,23,-24,24,-24,25,-24,26,-24,27,-24,28,-24,29,-24,30,-24,-1,0},
    /*41*/{3,6,4,14,5,10,6,15,7,16,14,8,20,17,-1,0},
    /*42*/{11,-6,-1,0},
    /*43*/{15,45,22,21,23,29,24,27,25,26,26,24,27,28,28,23,29,25,30,22,-1,0},
    /*44*/{11,-23,13,-23,15,-23,18,-23,22,-23,23,-23,24,-23,25,-23,26,-23,27,-23,28,-23,29,-23,30,-23,-1,0},
  };

  /** access to parse action table */
  public short[][] action_table() {return _action_table;}

  /** reduce_goto table */
  protected static final short[][] _reduce_table = {
    /*0*/{11,2,-1,-1},
    /*1*/{-1,-1},
    /*2*/{-1,-1},
    /*3*/{-1,-1},
    /*4*/{3,6,4,17,9,12,10,11,11,8,12,10,-1,-1},
    /*5*/{-1,-1},
    /*6*/{-1,-1},
    /*7*/{9,43,10,11,11,8,12,10,-1,-1},
    /*8*/{-1,-1},
    /*9*/{-1,-1},
    /*10*/{-1,-1},
    /*11*/{-1,-1},
    /*12*/{-1,-1},
    /*13*/{-1,-1},
    /*14*/{-1,-1},
    /*15*/{-1,-1},
    /*16*/{9,19,10,11,11,8,12,10,-1,-1},
    /*17*/{-1,-1},
    /*18*/{-1,-1},
    /*19*/{-1,-1},
    /*20*/{9,37,10,11,11,8,12,10,-1,-1},
    /*21*/{9,36,10,11,11,8,12,10,-1,-1},
    /*22*/{9,35,10,11,11,8,12,10,-1,-1},
    /*23*/{9,34,10,11,11,8,12,10,-1,-1},
    /*24*/{9,33,10,11,11,8,12,10,-1,-1},
    /*25*/{9,32,10,11,11,8,12,10,-1,-1},
    /*26*/{9,31,10,11,11,8,12,10,-1,-1},
    /*27*/{9,30,10,11,11,8,12,10,-1,-1},
    /*28*/{9,29,10,11,11,8,12,10,-1,-1},
    /*29*/{-1,-1},
    /*30*/{-1,-1},
    /*31*/{-1,-1},
    /*32*/{-1,-1},
    /*33*/{-1,-1},
    /*34*/{-1,-1},
    /*35*/{-1,-1},
    /*36*/{-1,-1},
    /*37*/{-1,-1},
    /*38*/{9,39,10,11,11,8,12,10,-1,-1},
    /*39*/{-1,-1},
    /*40*/{-1,-1},
    /*41*/{3,42,9,12,10,11,11,8,12,10,-1,-1},
    /*42*/{-1,-1},
    /*43*/{-1,-1},
    /*44*/{-1,-1},
  };

  /** access to reduce_goto table */
  public short[][] reduce_table() {return _reduce_table;}

  /** instance of action encapsulation class */
  protected CUP$actions_Call action_obj;

  /** action encapsulation object initializer */
  protected void init_actions()
    {
      action_obj = new CUP$actions_Call();
    }

  /** invoke a user supplied parse action */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$do_action(act_num, parser, stack, top);
  }

  /** start state */
  public int start_state() {return 0;}
  /** start production */
  public int start_production() {return 0;}

  /** EOF Symbol index */
  public int EOF_sym() {return 0;}

  /** error Symbol index */
  public int error_sym() {return 1;}


  /** user initialization */
  public void user_init() throws java.lang.Exception
    {
 

if (yylex == null) 
  System.err.println("WARNING: yylex must be initialized!");


    }

  /** scan to get the next Symbol */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return yylex.yylex(); 
    }



  private Yylex yylex;

  void assignLex(Yylex yylex) {
    this.yylex = yylex;
  }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$actions_Call {

  /** Constructor */
  CUP$actions_Call() { }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$do_action(
    int                        CUP$act_num,
    java_cup.runtime.lr_parser CUP$parser,
    java.util.Stack            CUP$stack,
    int                        CUP$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$result;

      /* select the action based on the action number */
      switch (CUP$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // abortStatement ::= ABORT LOOP CONSTANT SEMICOLON 
            {
              AbortLoopStatement RESULT = null;
		int numleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		TokenValue num = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{abortStatement ::= ABORT LOOP CONSTANT SEMICOLON}");}
				RESULT = new AbortLoopStatement(num.numberValue);
			
              CUP$result = new java_cup.runtime.Symbol(19/*abortStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // quitStatement ::= QUIT BLOCK CONSTANT SEMICOLON 
            {
              QuitBlockStatement RESULT = null;
		int numleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		TokenValue num = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{quitStatement ::= QUIT BLOCK CONSTANT SEMICOLON}");}
				RESULT = new QuitBlockStatement(num.numberValue);
			
              CUP$result = new java_cup.runtime.Symbol(18/*quitStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // assignStatement ::= CELL LPAREN expression RPAREN ASSIGN expression SEMICOLON 
            {
              AssignmentStatement RESULT = null;
		int indexleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).left;
		int indexright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).right;
		Expression index = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		Expression value = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{assignStatement ::= CELL LPAREN expression RPAREN ASSIGN expression SEMICOLON}");}
				RESULT = new AssignmentStatement(index, value);
			
              CUP$result = new java_cup.runtime.Symbol(17/*assignStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-6)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // assignStatement ::= OUTPUT ASSIGN expression SEMICOLON 
            {
              AssignmentStatement RESULT = null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		Expression value = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{assignStatement ::= OUTPUT ASSIGN expression SEMICOLON}");}
				RESULT = new AssignmentStatement(null, value);
			
              CUP$result = new java_cup.runtime.Symbol(17/*assignStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // ifStatement ::= IF expression COMMA THEN COLON statement 
            {
              IfStatement RESULT = null;
		int testleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).left;
		int testright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).right;
		Expression test = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-4)).value;
		int thenleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int thenright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Statement then = (Statement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{ifStatement ::= IF expression:test COMMA THEN COLON atement:then}");}
				RESULT = new IfStatement(test, then);
			
              CUP$result = new java_cup.runtime.Symbol(16/*ifStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-5)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // loopStatement ::= LOOP expression TIMES COLON blockStatement 
            {
              LoopStatement RESULT = null;
		int limitleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left;
		int limitright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).right;
		Expression limit = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		BlockStatement body = (BlockStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{loopStatement ::= LOOP expression TIMES COLON blockStatement}");}
				RESULT = new LoopStatement(limit, body, false);
			
              CUP$result = new java_cup.runtime.Symbol(15/*loopStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // loopStatement ::= LOOP AT MOST expression TIMES COLON blockStatement 
            {
              LoopStatement RESULT = null;
		int limitleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left;
		int limitright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).right;
		Expression limit = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		BlockStatement body = (BlockStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{loopStatement ::= LOOP AT MOST expression TIMES COLON blockStatement}");}
				RESULT = new LoopStatement(limit, body, true);
			
              CUP$result = new java_cup.runtime.Symbol(15/*loopStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-6)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // blockStatement ::= codeBlock SEMICOLON 
            {
              BlockStatement RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		Block b = (Block)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{blockStatement ::= codeBlock SEMICOLON}");}
				RESULT = new BlockStatement(b);
			
              CUP$result = new java_cup.runtime.Symbol(14/*blockStatement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // statement ::= abortStatement 
            {
              Statement RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		AbortLoopStatement stmt = (AbortLoopStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statement ::= abortStatement}");}
				RESULT = (Statement)stmt;
			
              CUP$result = new java_cup.runtime.Symbol(13/*statement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // statement ::= quitStatement 
            {
              Statement RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		QuitBlockStatement stmt = (QuitBlockStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statement ::= quitStatement}");}
				RESULT = (Statement)stmt;
			
              CUP$result = new java_cup.runtime.Symbol(13/*statement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // statement ::= assignStatement 
            {
              Statement RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		AssignmentStatement stmt = (AssignmentStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statement ::= assignStatement}");}
				RESULT = (Statement)stmt;
			
              CUP$result = new java_cup.runtime.Symbol(13/*statement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // statement ::= ifStatement 
            {
              Statement RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		IfStatement stmt = (IfStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statement ::= ifStatement}");}
				RESULT = (Statement)stmt;
			
              CUP$result = new java_cup.runtime.Symbol(13/*statement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // statement ::= loopStatement 
            {
              Statement RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		LoopStatement stmt = (LoopStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statement ::= loopStatement}");}
				RESULT = (Statement)stmt;
			
              CUP$result = new java_cup.runtime.Symbol(13/*statement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // statement ::= blockStatement 
            {
              Statement RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		BlockStatement stmt = (BlockStatement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statement ::= blockStatement}");}
				RESULT = (Statement)stmt;
			
              CUP$result = new java_cup.runtime.Symbol(13/*statement*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // codeBlock ::= BLOCK CONSTANT COLON BEGIN statementList BLOCK CONSTANT COLON END 
            {
              Block RESULT = null;
		int num1left = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-7)).left;
		int num1right = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-7)).right;
		TokenValue num1 = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-7)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).right;
		StatementList body = (StatementList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-4)).value;
		int num2left = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int num2right = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		TokenValue num2 = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{codeBlock ::= BLOCK CONSTANT COLON BEGIN statementList BLOCK CONSTANT COLON END}");}
				if(NaturalNumber.Compare(num1.numberValue, num2.numberValue) != 0)
				{
					//handle error?
					RESULT = null;
				}
				RESULT = new Block(num1.numberValue, body);
			
              CUP$result = new java_cup.runtime.Symbol(8/*codeBlock*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-8)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // procedureDef ::= DEFINE PROCEDURE QUOTE IDENTIFIER QUOTE LBRACKET identifierList RBRACKET COLON codeBlock PERIOD 
            {
              ProcedureDefinition RESULT = null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-7)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-7)).right;
		TokenValue name = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-7)).value;
		int fargsleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).left;
		int fargsright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-4)).right;
		IdentifierList fargs = (IdentifierList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-4)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		Block body = (Block)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{procedureDef ::= DEFINE PROCEDURE QUOTE IDENTIFIER QUOTE LBRACKET identifierList RBRACKET COLON codeBlock PERIOD}");}
				RESULT = new ProcedureDefinition(name.identifierValue, fargs, new BlockStatement(body));
			
              CUP$result = new java_cup.runtime.Symbol(2/*procedureDef*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-10)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // operatorExp ::= expression REMAINDER expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression REMAINDER expression}");}
				RESULT = (OperatorExpression)new RemainderExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // operatorExp ::= expression QUOTIENT expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression QUOTIENT expression}");}
				RESULT = (OperatorExpression)new QuotientExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // operatorExp ::= expression MULTIPLY expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression MULTIPLY expression}");}
				RESULT = (OperatorExpression)new MultiplyExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // operatorExp ::= expression SUBTRACT expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression SUBTRACT expression}");}
				RESULT = (OperatorExpression)new SubtractExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // operatorExp ::= expression ADD expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression ADD expression}");}
				RESULT = (OperatorExpression)new AddExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // operatorExp ::= expression LESSTHAN expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression LESSTHAN expression}");}
				RESULT = (OperatorExpression)new LessThanExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // operatorExp ::= expression EQUALS expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression EQUALS expression}");}
				RESULT = (OperatorExpression)new EqualsExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // operatorExp ::= expression OR expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression OR expression}");}
				RESULT = (OperatorExpression)new OrExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // operatorExp ::= expression AND expression 
            {
              OperatorExpression RESULT = null;
		int leftArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int leftArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression leftArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int rightArgleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int rightArgright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression rightArg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= expression AND expression}");}
				RESULT = (OperatorExpression)new AndExpression(leftArg, rightArg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // operatorExp ::= NOT expression 
            {
              OperatorExpression RESULT = null;
		int argleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int argright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression arg = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{operatorExp ::= NOT expression}");}
				RESULT = (OperatorExpression)new NotExpression(arg);
			
              CUP$result = new java_cup.runtime.Symbol(12/*operatorExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // callExp ::= IDENTIFIER LBRACKET expList RBRACKET 
            {
              CallExpression RESULT = null;
		int procleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left;
		int procright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).right;
		TokenValue proc = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-3)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		ExpressionList list = (ExpressionList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{callExp ::= IDENTIFIER LBRACKET expList RBRACKET}");}
				RESULT = new CallExpression(proc.identifierValue, list);
			
              CUP$result = new java_cup.runtime.Symbol(11/*callExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cellExp ::= CELL LPAREN expression RPAREN 
            {
              CellExpression RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		Expression exp = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{cellExp ::= CELL LPAREN expression RPAREN}");}
				RESULT = new CellExpression(exp);
			
              CUP$result = new java_cup.runtime.Symbol(10/*cellExp*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-3)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expression ::= LBRACE expression RBRACE 
            {
              Expression RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		Expression exp = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= LBRACE expression RBRACE}");}
				RESULT = (Expression)exp;
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expression ::= operatorExp 
            {
              Expression RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		OperatorExpression exp = (OperatorExpression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= operatorExp}");}
				RESULT = (Expression)exp;
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expression ::= callExp 
            {
              Expression RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		CallExpression exp = (CallExpression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= callExp}");}
				RESULT = (Expression)exp;
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expression ::= cellExp 
            {
              Expression RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		CellExpression exp = (CellExpression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= cellExp}");}
				RESULT = (Expression)exp;
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expression ::= IDENTIFIER 
            {
              Expression RESULT = null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		TokenValue token = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= IDENTIFIER}");}
				RESULT = (Expression)new VariableExpression(token.identifierValue);
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expression ::= NO 
            {
              Expression RESULT = null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		TokenValue token = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= NO}");}
				RESULT = (Expression)new ConstantExpression(new Value(token.boolValue));
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expression ::= YES 
            {
              Expression RESULT = null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		TokenValue token = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= YES}");}
				RESULT = (Expression)new ConstantExpression(new Value(token.boolValue));
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expression ::= CONSTANT 
            {
              Expression RESULT = null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		TokenValue token = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expression ::= CONSTANT}");}
				RESULT = (Expression)new ConstantExpression(new Value(token.numberValue));
			
              CUP$result = new java_cup.runtime.Symbol(9/*expression*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statementList ::= statement 
            {
              StatementList RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Statement stmt = (Statement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statementList ::= statement}");}
				RESULT = new StatementList(stmt, null);
			
              CUP$result = new java_cup.runtime.Symbol(7/*statementList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statementList ::= statementList statement 
            {
              StatementList RESULT = null;
		int listleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		StatementList list = (StatementList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Statement stmt = (Statement)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{statementList ::= statement statementList}");}
				
				list.Append(stmt);
				RESULT = list;
			
              CUP$result = new java_cup.runtime.Symbol(7/*statementList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // identifierList ::= nonempty_identifierList 
            {
              IdentifierList RESULT = null;
		int listleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		IdentifierList list = (IdentifierList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{identifierList ::= nonempty_identifierList}");}
				RESULT = list;
			
              CUP$result = new java_cup.runtime.Symbol(6/*identifierList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // identifierList ::= 
            {
              IdentifierList RESULT = null;
		
				if(BlooPTerminal.debug) {System.out.println("{identifierList ::= }");}
				RESULT = null;
			
              CUP$result = new java_cup.runtime.Symbol(6/*identifierList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // nonempty_identifierList ::= IDENTIFIER 
            {
              IdentifierList RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{nonempty_identifierList ::= IDENTIFIER}");}
				RESULT = new IdentifierList(id.identifierValue, null);
			
              CUP$result = new java_cup.runtime.Symbol(5/*nonempty_identifierList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // nonempty_identifierList ::= IDENTIFIER COMMA nonempty_identifierList 
            {
              IdentifierList RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		IdentifierList list = (IdentifierList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{nonempty_identifierList ::= IDENTIFIER COMMA nonempty_identifierList}");}
				RESULT = new IdentifierList(id.identifierValue, list);
			
              CUP$result = new java_cup.runtime.Symbol(5/*nonempty_identifierList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expList ::= nonempty_expList 
            {
              ExpressionList RESULT = null;
		int listleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		ExpressionList list = (ExpressionList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{expList ::= nonempty_expList}");}
				RESULT = list;
			
              CUP$result = new java_cup.runtime.Symbol(4/*expList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expList ::= 
            {
              ExpressionList RESULT = null;
		
				if(BlooPTerminal.debug) {System.out.println("{expList ::= }");}
				RESULT = null;
			
              CUP$result = new java_cup.runtime.Symbol(4/*expList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // nonempty_expList ::= expression 
            {
              ExpressionList RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Expression exp = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{nonempty_expList ::= expression}");}
				RESULT = new ExpressionList(exp, null);
			
              CUP$result = new java_cup.runtime.Symbol(3/*nonempty_expList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // nonempty_expList ::= expression COMMA nonempty_expList 
            {
              ExpressionList RESULT = null;
		int expleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).right;
		Expression exp = (Expression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		ExpressionList list = (ExpressionList)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{nonempty_expList ::= expression COMMA nonempty_expList}");}
				RESULT = new ExpressionList(exp, list);
			
              CUP$result = new java_cup.runtime.Symbol(3/*nonempty_expList*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-2)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // program ::= callExp SEPARATOR 
            {
              Ast RESULT = null;
		int callleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int callright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		CallExpression call = (CallExpression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{program ::= callExp}");}
				RESULT = call;
			
              CUP$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // program ::= procedureDef SEPARATOR 
            {
              Ast RESULT = null;
		int procleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int procright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		ProcedureDefinition proc = (ProcedureDefinition)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{program ::= procedureDef}");}
				RESULT = proc;
			
              CUP$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= procedureDef callExp 
            {
              Ast RESULT = null;
		int procleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int procright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		ProcedureDefinition proc = (ProcedureDefinition)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		int callleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int callright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		CallExpression call = (CallExpression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{program ::= procedureDef callExp}");}
				RESULT = new Program(proc, call);
			
              CUP$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= procedureDef program 
            {
              Ast RESULT = null;
		int procleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int procright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		ProcedureDefinition proc = (ProcedureDefinition)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		int progleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).left;
		int progright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right;
		Ast prog = (Ast)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-0)).value;
		
				if(BlooPTerminal.debug) {System.out.println("{program ::= procedureDef program}");}
				RESULT = new Program(proc, prog);
			
              CUP$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          return CUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= callExp EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).right;
		CallExpression start_val = (CallExpression)((java_cup.runtime.Symbol) CUP$stack.elementAt(CUP$top-1)).value;
		RESULT = start_val;
              CUP$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-1)).left, ((java_cup.runtime.Symbol)CUP$stack.elementAt(CUP$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser.done_parsing();
          return CUP$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

