
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Sat Nov 24 15:48:11 PST 2001
//----------------------------------------------------

package org.dgould.geb.bloop;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int LBRACKET = 10;
  static final int OUTPUT = 8;
  static final int EQUALS = 24;
  static final int PERIOD = 19;
  static final int SUBTRACT = 27;
  static final int LPAREN = 12;
  static final int RPAREN = 13;
  static final int DEFINE = 42;
  static final int YES = 4;
  static final int NOT = 20;
  static final int SEMICOLON = 17;
  static final int AND = 22;
  static final int BLOCK = 31;
  static final int LESSTHAN = 25;
  static final int OR = 23;
  static final int COMMA = 18;
  static final int SEPARATOR = 2;
  static final int BEGIN = 32;
  static final int LOOP = 35;
  static final int MULTIPLY = 28;
  static final int IF = 40;
  static final int ASSIGN = 21;
  static final int QUOTE = 9;
  static final int MOST = 37;
  static final int EOF = 0;
  static final int ABORT = 39;
  static final int RBRACKET = 11;
  static final int error = 1;
  static final int ADD = 26;
  static final int CONSTANT = 3;
  static final int TIMES = 38;
  static final int COLON = 16;
  static final int QUIT = 34;
  static final int NO = 5;
  static final int LBRACE = 14;
  static final int THEN = 41;
  static final int RBRACE = 15;
  static final int END = 33;
  static final int REMAINDER = 30;
  static final int AT = 36;
  static final int CELL = 7;
  static final int QUOTIENT = 29;
  static final int PROCEDURE = 43;
  static final int IDENTIFIER = 6;
}

